## Test 1
force -freeze sim:/processor/in_port 16#FFFFFFFF 0
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
run $CLOCK_PERIOD
wave zoom full
