LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY demux_1to4 IS
    GENERIC (WIDTH : INTEGER := 32);
    PORT (
        input : IN STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0);
        sel : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
        output_0 : OUT STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0);
        output_1 : OUT STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0);
        output_2 : OUT STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0);
        output_3 : OUT STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0)
    );
END ENTITY demux_1to4;

ARCHITECTURE rtl OF demux_1to4 IS
BEGIN
    -- TODO: implement 1:4 demux
END ARCHITECTURE rtl;