LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY mux_4to1 IS
    GENERIC (WIDTH : INTEGER := 32);
    PORT (
        input_0 : IN STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0);
        input_1 : IN STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0);
        input_2 : IN STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0);
        input_3 : IN STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0);
        sel : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
        output : OUT STD_LOGIC_VECTOR(WIDTH - 1 DOWNTO 0)
    );
END ENTITY mux_4to1;

ARCHITECTURE rtl OF mux_4to1 IS
BEGIN
    -- TODO: implement 4:1 mux
END ARCHITECTURE rtl;